# Generated by Django 5.1.5 on 2025-01-19 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_alter_flat_has_balcony_alter_flat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='is_new_building',
            field=models.BooleanField(blank=True, db_index=True, null=True, verbose_name='Новостройка'),
        ),
    ]
