# Generated by Django 5.1.5 on 2025-01-19 14:22

from django.db import migrations
from property.models import Flat


def fill_is_new_building(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Flat.objects.filter(construction_year__gte=2015).update(
        is_new_building=True)
    Flat.objects.filter(construction_year__lt=2015).update(
        is_new_building=False)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_flat_is_new_building'),
    ]

    operations = [
        migrations.RunPython(fill_is_new_building)
    ]

