# Generated by Django 5.1.5 on 2025-01-19 14:22

from django.db import migrations
from property.models import Flat


def fill_is_new_building(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    flats = Flat.objects.all()

    for flat in flats:
        if flat.construction_year and flat.construction_year >= 2015:
            flat.is_new_building = True
        else:
            flat.is_new_building = False
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_flat_is_new_building'),
    ]

    operations = [
        migrations.RunPython(fill_is_new_building)
    ]
