# Generated by Django 5.1.5 on 2025-01-20 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_remove_owner_flats_propertyownerownedflats_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='owners',
        ),
    ]
