# Generated by Django 5.1.5 on 2025-01-21 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_remove_flat_owners'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='flats',
        ),
        migrations.AddField(
            model_name='flat',
            name='owners',
            field=models.ManyToManyField(related_name='flats_owned', through='property.PropertyOwnerOwnedFlats', to='property.owner'),
        ),
    ]
