# Generated by Django 5.1.5 on 2025-01-28 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0016_remove_owner_flats_flat_owners'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyownerownedflats',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='propertyownerownedflats',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='propertyownerownedflats',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='flat',
            name='owners',
            field=models.ManyToManyField(related_name='flats', through='property.PropertyOwnerOwnedFlats', to='property.owner'),
        ),
        migrations.AlterField(
            model_name='propertyownerownedflats',
            name='flat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.flat'),
        ),
        migrations.AlterField(
            model_name='propertyownerownedflats',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.owner'),
        ),
    ]
