# Generated by Django 5.1.3 on 2025-01-28 14:11

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0017_alter_propertyownerownedflats_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='flats2',
            field=models.ManyToManyField(blank=True, related_name='property_owners', to='property.flat'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='owner_pure_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Нормализованный номер владельца'),
        ),
    ]
